version: "3.3"
services:
  client: &client
    hostname: client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
      VUE_APP_API: "http://192.168.31.57:8080/api"
    volumes:
      - ./client:/home/node/app:cached
      - client_node_modules:/home/node/app/node_modules:rw
    entrypoint: yarn dev

  server: &server
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      NODE_ENV: "development"
      CLIENT: ""
      
  session:
    ports:
      - "6379:6379"

  ### shell
  fshell:
    <<: *client
    entrypoint: /bin/bash
  bshell:
    <<: *server
    entrypoint: /bin/bash

  db:
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=msa
      - MYSQL_ROOT_HOST=%