version: "3.3"
services:
  client: &client
    hostname: client
    networks:
      - frontend
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
      VUE_APP_API: "http://192.168.31.57:8080/api"
    volumes:
      - ./client:/home/node/app:cached
      - client_node_modules:/home/node/app/node_modules:rw
    entrypoint: /bin/bash

  server: &server
    networks:
      - frontend
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      NODE_ENV: "development"
      CLIENT: "http://client:3000"
    entrypoint: /bin/bash
      
  session:
    ports:
      - "6379:6379"

  db:
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=msa
      - MYSQL_ROOT_HOST=%